# Generated by Django 2.2.1 on 2019-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
