# Generated by Django 2.2.1 on 2019-09-18 11:23

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190917_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.post.models.upload_image_path),
        ),
    ]
