# Generated by Django 2.2.1 on 2019-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
    ]
